global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 10s
  receiver: 'log'
receivers:
- name: 'log'
  log_configs:
    - file_path: '/tmp/test.log'
      logger: logfmt
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
